spring:
  application:
    name: config-git-client
  cloud:
    bus:
      trace:
        enabled: true
      enabled: true
server:
  port: 13001
management:
  endpoints:
    web:
      exposure:
        include: "refresh"